load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["keys.go"],
    importpath = "go-webview-wasm/js/keys",
    visibility = ["//visibility:public"],
)
